version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    labels:
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    target-branch: "1.x"
    labels:
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"
